# Generated by Django 5.2.5 on 2025-08-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Сотрудник", "verbose_name_plural": "Сотрудники"},
        ),
    ]
