# Generated by Django 5.2.5 on 2025-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("employee", "Сотрудник"),
                    ("team_leader", "Руководитель"),
                    ("director", "Директор"),
                ],
                default="",
                help_text="Укажите должность",
                max_length=100,
                verbose_name="Должность",
            ),
        ),
    ]
