# Generated by Django 5.2.5 on 2025-08-23 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "task_name",
                    models.CharField(
                        help_text="Укажите наименование задачи", max_length=200, verbose_name="Наименование задачи"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        help_text="Укажите время, до которого нужно выполнить задачу", verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "создана"),
                            ("needs_clarification", "требует уточнения"),
                            ("in_process", "в работе"),
                            ("under_review", "на проверке"),
                            ("completed", "выполнена"),
                            ("cancelled", "отменена"),
                        ],
                        default="created",
                        help_text="Укажите статус задания",
                        max_length=30,
                        verbose_name="Статус задания",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(
                        default=False,
                        help_text="Определяет является ли задача важной, т.е. зависят ли от неё другие задачи",
                        verbose_name="Признак важной задачи",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Определяет является ли задача главной, т.е. есть ли у неё дочерние задачи",
                        verbose_name="Признак главной задачи",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        help_text="Укажите исполнителя задания",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Укажите автора задания",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор задания",
                    ),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите задачу, выполнение которой связано с реализацией данной задачи.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.task",
                        verbose_name="Связанная задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "unique_together": {("owner", "executor", "task_name", "deadline")},
            },
        ),
    ]
