# Generated by Django 5.2.5 on 2025-08-23 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_important",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_main",
        ),
        migrations.RemoveField(
            model_name="task",
            name="related_task",
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Укажите описание задачи", verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите родительскую задачу",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="tasks.task",
                verbose_name="Родительская задача",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Низкий"), (2, "Средний"), (3, "Высокий")],
                default=1,
                help_text="Укажите приоритет задания",
                verbose_name="Приоритет",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="time_completed",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время завершения"),
        ),
        migrations.AddField(
            model_name="task",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Время создания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="time_started",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время начала работы"),
        ),
        migrations.AddField(
            model_name="task",
            name="time_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Время обновления"),
        ),
    ]
