# Generated by Django 5.2.5 on 2025-08-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_task_is_important_remove_task_is_main_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("needs_clarification", "требует уточнения"),
                    ("in_process", "в работе"),
                    ("under_review", "на проверке"),
                    ("completed", "выполнена"),
                    ("cancelled", "отменена"),
                ],
                default="created",
                help_text="Укажите статус задания",
                max_length=30,
                verbose_name="Статус задания",
            ),
        ),
    ]
