# Generated by Django 5.2.5 on 2025-08-24 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                help_text="Укажите исполнителя задания",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executor_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                help_text="Укажите автора задания",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор задания",
            ),
        ),
    ]
